package com.cinemateca.domain.trailers.model

enum class TrailerGenre(val value: String) {
    ADVENTURE("Adventure"),
    DRAMA("Drama"),
    HORROR("Horror"),
    COMEDY("Comedy"),
    ANIMATION("Animation"),
    FAMILY("Family"),
    SCIENCE_FICTION("Science Fiction"),
    ACTION("Action"),
    THRILLER("Thriller"),
    MYSTERY("Mystery"),
    CRIME("Crime"),
    FANTASY("Fantasy"),
    ROMANCE("Romance"),
    WESTERN("Western"),
    DOCUMENTARY("Documentary"),
    HISTORY("History"),
    MUSIC("Music"),
    WAR("War"),
    FOREIGN("Foreign"),
    TV_MOVIE("TV Movie"),
    BIOPIC("Biopic"),
    SCI_FI_AND_FANTASY("Sci-Fi & Fantasy"),
    ACTION_AND_ADVENTURE("Action & Adventure"),
    SPORT("Sport"),
    INDEPENDENT("Independent"),
    KIDS("Kids"),
    REALITY_TV("Reality-TV"),
    SUPERHERO("Superhero"),
}
